version: 1.2
workflows:
  - subclass: WDL
    primaryDescriptorPath: /workflows/get_samples_from_runs.wdl
    testParameterFiles:
      - /workflows/get_samples_from_runs.json
    authors:
      - orcid: 0000-0003-4896-1858
  - subclass: WDL
    primaryDescriptorPath: /workflows/get_organisms_from_bioproject.wdl
    testParameterFiles:
      - /workflows/get_organisms_from_bioproject.json
    authors:
      - orcid: 0000-0003-4896-1858
  - subclass: WDL
    primaryDescriptorPath: /workflows/pull_paired_FASTQ_by_biosample.wdl
    testParameterFiles:
      - /workflows/pull_paired_FASTQ_by_biosample.json
    authors:
      - orcid: 0000-0003-4896-1858
  - subclass: WDL
    primaryDescriptorPath: /workflows/pull_paired_FASTQ_by_run_accession.wdl
    authors:
      - orcid: 0000-0003-4896-1858